version: '3'

services:

    sddgen:
        build: ./
        restart: always
        container_name: SDD-Gen
        tty: true
        ports:
            - "5000:5000"
        volumes:
            - $PWD/cert:/app/cert

volumes:
    cert:
