version: '3'

services:
    # The primary sdd-gen web app
    sddgen:
        build: ./
        restart: always
        container_name: sddgen
        tty: true
        ports:
            - "5000:5000"
        networks:
            sddgen:
                aliases:
                    - sddgen
        volumes:
            - $PWD/cert:/app/cert

   # The sdd-gen fuseki instance
    # fuseki:
    #     build:
    #         context: ./fuseki
    #         dockerfile: Dockerfile
    #     container_name: sddgen_fuseki
    #     networks:
    #         sddgen:
    #             aliases:
    #                 - sddgen
    #     ports:
    #         - "3030:3030"
    #     restart: always
    #     environment:
    #         JAVA_XMS: 512m
    #         JAVA_XMX: 4g
    #     volumes:
    #         - sddgen-fuseki:/usr/share/data atomgraph/fuseki

volumes:
    cert:
    # sddgen-fuseki:

networks:
    sddgen:
